### ISSUE TITLE
Can you share the code for predicting？

### ISSUE THREAD

**Issue by x505367603** [Jia-Research-Lab/PanopticFCN#11]

**Comment by yanwei-li** [comment]
Hi, I'm not sure the meaning of predicting. Actually, you can follow the procedures in ```Installation``` and utilize [Detectron2 ](https://github.com/facebookresearch/detectron2)for training and evaluation.

**Comment by x505367603** [comment]
> Hi, I'm not sure the meaning of predicting. Actually, you can follow the procedures in `Installation` and utilize [Detectron2 ](https://github.com/facebookresearch/detectron2)for training and evaluation.

I mean, input a set of photos and use the trained panoramic segmentation model to predict the objects in these photos. Thank you for your reply!

**Comment by x505367603** [comment]
> Hi, I'm not sure the meaning of predicting. Actually, you can follow the procedures in `Installation` and utilize [Detectron2 ](https://github.com/facebookresearch/detectron2)for training and evaluation.

I mean, input a set of photos and use the trained panoptic segmentation model to predict the objects in these photos. Thank you for your reply!

**Comment by yanwei-li** [comment]
Hi, for demo visualization, you can utilize the ```demo/demo.py``` in [Detectron2](https://github.com/facebookresearch/detectron2), with a simple modification. Please to the comment in this [issue](https://github.com/Jia-Research-Lab/PanopticFCN/issues/10#issuecomment-792733929).

**Comment by x505367603** [comment]
> Hi, for demo visualization, you can utilize the `demo/demo.py` in [Detectron2](https://github.com/facebookresearch/detectron2), with a simple modification. Please to the comment in this [issue](https://github.com/Jia-Research-Lab/PanopticFCN/issues/10#issuecomment-792733929).

Ok, thank you.
